-- Add a short pickup code to orders. Generated by the stripe-webhook, shown to the
-- customer on the confirmation page and to the kitchen on the dashboard; the customer
-- reads it out at pickup. Run in the Supabase SQL editor before deploying the updated
-- functions. Safe to re-run (IF NOT EXISTS).

alter table orders
  add column if not exists pickup_code text;

-- Speeds up the uniqueness check the webhook runs against active orders.
create index if not exists orders_pickup_code_idx on orders (pickup_code);
